import org.apache.commons.text.WordUtils;

import java.util.*;

public class Reformat {
	
	public static final List<String> SKILLS = new ArrayList<>();
	public static final List<String> ITEMS  = new ArrayList<>();
	//public static final String       STRING_LITERAL;
	
	public static final Map<String, String> ABBREVIATIONS = new HashMap<>();
	public static final Set<String>         GRAMMAR       = new HashSet<>();
	public static final Map<String, String> HARDCODES     = new HashMap<>();
	
	//public static final Pattern NO_DUPE;
	
	static {
		SKILLS.add("Magic Arrow");
		SKILLS.add("Fire Arrow");
		SKILLS.add("Inner Sight");
		SKILLS.add("Critical Strike");
		SKILLS.add("Jab");
		SKILLS.add("Cold Arrow");
		SKILLS.add("Multiple Shot");
		SKILLS.add("Dodge");
		SKILLS.add("Power Strike");
		SKILLS.add("Poison Javelin");
		SKILLS.add("Exploding Arrow");
		SKILLS.add("Slow Missiles");
		SKILLS.add("Avoid");
		SKILLS.add("Impale");
		SKILLS.add("Lightning Bolt");
		SKILLS.add("Ice Arrow");
		SKILLS.add("Guided Arrow");
		SKILLS.add("Penetrate");
		SKILLS.add("Charged Strike");
		SKILLS.add("Plague Javelin");
		SKILLS.add("Strafe");
		SKILLS.add("Immolation Arrow");
		SKILLS.add("Decoy");
		SKILLS.add("Evade");
		SKILLS.add("Fend");
		SKILLS.add("Freezing Arrow");
		SKILLS.add("Valkyrie");
		SKILLS.add("Pierce");
		SKILLS.add("Lightning Strike");
		SKILLS.add("Lightning Fury");
		SKILLS.add("Fire Bolt");
		SKILLS.add("Warmth");
		SKILLS.add("Charged Bolt");
		SKILLS.add("Ice Bolt");
		SKILLS.add("Frozen Armor");
		SKILLS.add("Inferno");
		SKILLS.add("Static Field");
		SKILLS.add("Telekinesis");
		SKILLS.add("Frost Nova");
		SKILLS.add("Ice Blast");
		SKILLS.add("Blaze");
		SKILLS.add("Fire Ball");
		SKILLS.add("Nova");
		SKILLS.add("Lightning");
		SKILLS.add("Shiver Armor");
		SKILLS.add("Fire Wall");
		SKILLS.add("Enchant");
		SKILLS.add("Chain Lightning");
		SKILLS.add("Teleport");
		SKILLS.add("Glacial Spike");
		SKILLS.add("Meteor");
		SKILLS.add("Thunder Storm");
		SKILLS.add("Energy Shield");
		SKILLS.add("Blizzard");
		SKILLS.add("Chilling Armor");
		SKILLS.add("Fire Mastery");
		SKILLS.add("Hydra");
		SKILLS.add("Lightning Mastery");
		SKILLS.add("Frozen Orb");
		SKILLS.add("Cold Mastery");
		SKILLS.add("Amplify Damage");
		SKILLS.add("Teeth");
		SKILLS.add("Bone Armor");
		SKILLS.add("Skeleton Mastery");
		SKILLS.add("Raise Skeleton");
		SKILLS.add("Dim Vision");
		SKILLS.add("Weaken");
		SKILLS.add("Poison Dagger");
		SKILLS.add("Corpse Explosion");
		SKILLS.add("Clay Golem");
		SKILLS.add("Iron Maiden");
		SKILLS.add("Terror");
		SKILLS.add("Bone Wall");
		SKILLS.add("Golem Mastery");
		SKILLS.add("Skeletal Mage");
		SKILLS.add("Confuse");
		SKILLS.add("Life Tap");
		SKILLS.add("Poison Explosion");
		SKILLS.add("Bone Spear");
		SKILLS.add("Blood Golem");
		SKILLS.add("Attract");
		SKILLS.add("Decrepify");
		SKILLS.add("Bone Prison");
		SKILLS.add("Summon Resist");
		SKILLS.add("Iron Golem");
		SKILLS.add("Lower Resist");
		SKILLS.add("Poison Nova");
		SKILLS.add("Bone Spirit");
		SKILLS.add("Fire Golem");
		SKILLS.add("Revive");
		SKILLS.add("Sacrifice");
		SKILLS.add("Smite");
		SKILLS.add("Might");
		SKILLS.add("Prayer");
		SKILLS.add("Resist Fire");
		SKILLS.add("Holy Bolt");
		SKILLS.add("Holy Fire");
		SKILLS.add("Thorns");
		SKILLS.add("Defiance");
		SKILLS.add("Resist Cold");
		SKILLS.add("Zeal");
		SKILLS.add("Charge");
		SKILLS.add("Blessed Aim");
		SKILLS.add("Cleansing");
		SKILLS.add("Resist Lightning");
		SKILLS.add("Vengeance");
		SKILLS.add("Blessed Hammer");
		SKILLS.add("Concentration");
		SKILLS.add("Holy Freeze");
		SKILLS.add("Vigor");
		SKILLS.add("Conversion");
		SKILLS.add("Holy Shield");
		SKILLS.add("Holy Shock");
		//SKILLS.add("Sanctuary");
		SKILLS.add("Meditation");
		SKILLS.add("Fist of the Heavens");
		SKILLS.add("Fanaticism");
		SKILLS.add("Conviction");
		SKILLS.add("Redemption");
		SKILLS.add("Salvation");
		SKILLS.add("Bash");
		SKILLS.add("Sword Mastery");
		SKILLS.add("Axe Mastery");
		SKILLS.add("Mace Mastery");
		SKILLS.add("Howl");
		SKILLS.add("Find Potion");
		SKILLS.add("Leap");
		SKILLS.add("Double Swing");
		SKILLS.add("Polearm Mastery");
		SKILLS.add("Throwing Mastery");
		SKILLS.add("Spear Mastery");
		SKILLS.add("Taunt");
		SKILLS.add("Shout");
		SKILLS.add("Stun");
		SKILLS.add("Double Throw");
		SKILLS.add("Increased Stamina");
		SKILLS.add("Find Item");
		SKILLS.add("Leap Attack");
		SKILLS.add("Concentrate");
		SKILLS.add("Iron Skin");
		SKILLS.add("Battle Cry");
		SKILLS.add("Frenzy");
		SKILLS.add("Increased Speed");
		SKILLS.add("Battle Orders");
		SKILLS.add("Grim Ward");
		SKILLS.add("Whirlwind");
		SKILLS.add("Berserk");
		SKILLS.add("Natural Resistance");
		SKILLS.add("War Cry");
		SKILLS.add("Battle Command");
		SKILLS.add("Raven");
		SKILLS.add("Poison Creeper");
		SKILLS.add("Werewolf");
		SKILLS.add("Lycanthropy");
		SKILLS.add("Firestorm");
		SKILLS.add("Oak Sage");
		SKILLS.add("Summon Spirit Wolf");
		SKILLS.add("Summon Dire Wolf");
		SKILLS.add("Werebear");
		SKILLS.add("Molten Boulder");
		SKILLS.add("Arctic Blast");
		SKILLS.add("Carrion Vine");
		SKILLS.add("Feral Rage");
		SKILLS.add("Maul");
		SKILLS.add("Fissure");
		SKILLS.add("Cyclone Armor");
		SKILLS.add("Heart of Wolverine");
		SKILLS.add("Solar Creeper");
		SKILLS.add("Rabies");
		SKILLS.add("Fire Claws");
		SKILLS.add("Twister");
		SKILLS.add("Hunger");
		SKILLS.add("Shock Wave");
		SKILLS.add("Volcano");
		SKILLS.add("Tornado");
		SKILLS.add("Spirit of Barbs");
		SKILLS.add("Summon Grizzly");
		SKILLS.add("Fury");
		SKILLS.add("Armageddon");
		SKILLS.add("Hurricane");
		SKILLS.add("Fire Blast");
		SKILLS.add("Claw Mastery");
		SKILLS.add("Psychic Hammer");
		SKILLS.add("Tiger Strike");
		SKILLS.add("Dragon Talon");
		SKILLS.add("Shock Web");
		SKILLS.add("Blade Sentinel");
		SKILLS.add("Burst of Speed");
		SKILLS.add("Fists of Fire");
		SKILLS.add("Dragon Claw");
		SKILLS.add("Charged Bolt Sentry");
		SKILLS.add("Wake of Fire Sentry");
		SKILLS.add("Weapon Block");
		SKILLS.add("Cloak of Shadows");
		SKILLS.add("Cobra Strike");
		SKILLS.add("Blade Fury");
		SKILLS.add("Fade");
		SKILLS.add("Shadow Warrior");
		SKILLS.add("Claws of Thunder");
		SKILLS.add("Dragon Tail");
		SKILLS.add("Lightning Sentry");
		SKILLS.add("Inferno Sentry");
		SKILLS.add("Mind Blast");
		SKILLS.add("Blades of Ice");
		SKILLS.add("Dragon Flight");
		SKILLS.add("Death Sentry");
		SKILLS.add("Blade Shield");
		SKILLS.add("Venom");
		SKILLS.add("Shadow Master");
		SKILLS.add("Phoenix Strike");
		
		SKILLS.sort(Comparator.comparingInt(String::length).reversed());
		
		// THINGS
		ITEMS.add("Gnasher");
		ITEMS.add("Deathspade");
		ITEMS.add("Bladebone");
		ITEMS.add("Mindrend");
		ITEMS.add("Rakescar");
		ITEMS.add("Axe of Fechmar");
		ITEMS.add("Goreshovel");
		ITEMS.add("Chieftan");
		ITEMS.add("Brainhew");
		ITEMS.add("Humongous");
		ITEMS.add("Torch of Iro");
		ITEMS.add("Maelstrom");
		ITEMS.add("Gravenspine");
		ITEMS.add("Ume’s Lament");
		ITEMS.add("Felloak");
		ITEMS.add("Knell Striker");
		ITEMS.add("Rusthandle");
		ITEMS.add("Stormeye");
		ITEMS.add("Stoutnail");
		ITEMS.add("Crushflange");
		ITEMS.add("Bloodrise");
		ITEMS.add("General’s Tan Do Li Ga");
		ITEMS.add("Ironstone");
		ITEMS.add("Bonesnap");
		ITEMS.add("Steeldriver");
		ITEMS.add("Rixot’s Keen");
		ITEMS.add("Blood Crescent");
		ITEMS.add("Skewer of Krintiz");
		ITEMS.add("Gleamscythe");
		ITEMS.add("Azurewrath");
		ITEMS.add("Griswold’s Edge");
		ITEMS.add("Hellplague");
		ITEMS.add("Culwen’s Point");
		ITEMS.add("Shadowfang");
		ITEMS.add("Soulflay");
		ITEMS.add("Kinemil’s Awl");
		ITEMS.add("Blacktongue");
		ITEMS.add("Ripsaw");
		ITEMS.add("Patriarch");
		ITEMS.add("Gull");
		ITEMS.add("Diggler");
		ITEMS.add("Jade Tan Do");
		ITEMS.add("Spectral Shard");
		ITEMS.add("Dragon Chang");
		ITEMS.add("Razortine");
		ITEMS.add("Bloodthief");
		ITEMS.add("Lance of Yaggai");
		ITEMS.add("Tannr Gorerod");
		ITEMS.add("Dimoak’s Hew");
		ITEMS.add("Steelgoad");
		ITEMS.add("Soul Harvest");
		ITEMS.add("Battlebranch");
		ITEMS.add("Woestave");
		ITEMS.add("Grim Reaper");
		ITEMS.add("Bane Ash");
		ITEMS.add("Serpent Lord");
		ITEMS.add("Lazarus Spire");
		ITEMS.add("Salamander");
		ITEMS.add("Iron Jang Bong");
		ITEMS.add("Pluckeye");
		ITEMS.add("Witherstring");
		ITEMS.add("Rimeraven");
		ITEMS.add("Piercerib");
		ITEMS.add("Pullspite");
		ITEMS.add("Wizendraw");
		ITEMS.add("Hellclap");
		ITEMS.add("Blastbark");
		ITEMS.add("Leadcrow");
		ITEMS.add("Ichorsting");
		ITEMS.add("Hellcast");
		ITEMS.add("Doomspittle");
		ITEMS.add("War Bonnet");
		ITEMS.add("Tarnhelm");
		ITEMS.add("Coif of Glory");
		ITEMS.add("Duskdeep");
		ITEMS.add("Wormskull");
		ITEMS.add("Howltusk");
		ITEMS.add("Undead Crown");
		ITEMS.add("Face of Horror");
		ITEMS.add("Greyform");
		ITEMS.add("Blinkbat’s Form");
		ITEMS.add("Centurion");
		ITEMS.add("Twitchthroe");
		ITEMS.add("Darkglow");
		ITEMS.add("Hawkmail");
		ITEMS.add("Sparking Mail");
		ITEMS.add("Venomsward");
		ITEMS.add("Iceblink");
		ITEMS.add("Boneflesh");
		ITEMS.add("Rockfleece");
		ITEMS.add("Rattlecage");
		ITEMS.add("Goldskin");
		ITEMS.add("Silks of the Victor");
		ITEMS.add("Heavenly Garb");
		ITEMS.add("Pelta Lunata");
		ITEMS.add("Umbral Disk");
		ITEMS.add("Stormguild");
		ITEMS.add("Wall of the Eyeless");
		ITEMS.add("Swordback Hold");
		ITEMS.add("Steelclash");
		ITEMS.add("Bverrit Keep");
		ITEMS.add("Ward");
		ITEMS.add("Hand of Broc");
		ITEMS.add("Bloodfist");
		ITEMS.add("Chance Guards");
		ITEMS.add("Magefist");
		ITEMS.add("Frostburn");
		ITEMS.add("Hotspur");
		ITEMS.add("Gorefoot");
		ITEMS.add("Treads of Cthon");
		ITEMS.add("Goblin Toe");
		ITEMS.add("Tearhaunch");
		ITEMS.add("Lenyms Cord");
		ITEMS.add("Snakecord");
		ITEMS.add("Nightsmoke");
		ITEMS.add("Goldwrap");
		ITEMS.add("Bladebuckle");
		ITEMS.add("Nokozan Relic");
		ITEMS.add("Eye of Etlich");
		ITEMS.add("Mahim-Oak Curio");
		ITEMS.add("Nagelring");
		ITEMS.add("Manald Heal");
		ITEMS.add("Stone of Jordan");
		ITEMS.add("Coldkill");
		ITEMS.add("Butcher’s Pupil");
		ITEMS.add("Islestrike");
		ITEMS.add("Pompe’s Wrath");
		ITEMS.add("Guardian Naga");
		ITEMS.add("Warlord’s Trust");
		ITEMS.add("Spellsteel");
		ITEMS.add("Stormrider");
		ITEMS.add("Boneslayer Blade");
		ITEMS.add("Minotaur");
		ITEMS.add("Suicide Branch");
		ITEMS.add("Carin Shard");
		ITEMS.add("Arm of King Leoric");
		ITEMS.add("Blackhand Key");
		ITEMS.add("Dark Clan Crusher");
		ITEMS.add("Zakarum’s Hand");
		ITEMS.add("Fetid Sprinkler");
		ITEMS.add("Hand of Blessed Light");
		ITEMS.add("Fleshrender");
		ITEMS.add("Sureshrill Frost");
		ITEMS.add("Moonfall");
		ITEMS.add("Baezil’s Vortex");
		ITEMS.add("Earthshaker");
		ITEMS.add("Bloodtree Stump");
		ITEMS.add("Gavel of Pain");
		ITEMS.add("Bloodletter");
		ITEMS.add("Coldsteel Eye");
		ITEMS.add("Hexfire");
		ITEMS.add("Blade of Ali Baba");
		ITEMS.add("Ginther’s Rift");
		ITEMS.add("Headstriker");
		ITEMS.add("Soul Drainer");
		ITEMS.add("Plague Bearer");
		ITEMS.add("Atlantian");
		ITEMS.add("Crainte Vomir");
		ITEMS.add("Bing Sz Wang");
		ITEMS.add("Vile Husk");
		ITEMS.add("Cloudcrack");
		ITEMS.add("Todesfaelle Flamme");
		ITEMS.add("Swordguard");
		ITEMS.add("Spineripper");
		ITEMS.add("Heart Carver");
		ITEMS.add("Blackbog’s Sharp");
		ITEMS.add("Stormspike");
		ITEMS.add("Impaler");
		ITEMS.add("Kelpie Snare");
		ITEMS.add("Soulfeast Tine");
		ITEMS.add("Hone Sundan");
		ITEMS.add("Spire of Honor");
		ITEMS.add("Meat Scraper");
		ITEMS.add("Blackleach Blade");
		ITEMS.add("Athena’s Wrath");
		ITEMS.add("Pierre Tombale Couant");
		ITEMS.add("Husoldal Evo");
		ITEMS.add("Grim’s Burning Dead");
		ITEMS.add("Razorswitch");
		ITEMS.add("Ribcracker");
		ITEMS.add("Chromatic Ire");
		ITEMS.add("Warpspear");
		ITEMS.add("Skullcollector");
		ITEMS.add("Skystrike");
		ITEMS.add("Riphook");
		ITEMS.add("Kuko Shakaku");
		ITEMS.add("Endlesshail");
		ITEMS.add("Whichwild String");
		ITEMS.add("Cliffkiller");
		ITEMS.add("Magewrath");
		ITEMS.add("Goldstrike Arch");
		ITEMS.add("Langer Briser");
		ITEMS.add("Pus Spiter");
		ITEMS.add("Buriza-Do Kyanon");
		ITEMS.add("Demon Machine");
		ITEMS.add("Peasant Crown");
		ITEMS.add("Rockstopper");
		ITEMS.add("Stealskull");
		ITEMS.add("Darksight Helm");
		ITEMS.add("Valkyrie Wing");
		ITEMS.add("Crown of Thieves");
		ITEMS.add("Blackhorn’s Face");
		ITEMS.add("Vampire Gaze");
		ITEMS.add("Spirit Shroud");
		ITEMS.add("Skin of the Vipermagi");
		ITEMS.add("Skin of the Flayerd One");
		ITEMS.add("Iron Pelt");
		ITEMS.add("Spirit Forge");
		ITEMS.add("Crow Caw");
		ITEMS.add("Shaftstop");
		ITEMS.add("Duriel’s Shell");
		ITEMS.add("Skullder’s Ire");
		ITEMS.add("Guardian Angel");
		ITEMS.add("Toothrow");
		ITEMS.add("Atma’s Wail");
		ITEMS.add("Black Hades");
		ITEMS.add("Corpsemourn");
		ITEMS.add("Que-Hegan’s Wisdom");
		ITEMS.add("Visceratuant");
		ITEMS.add("Moser’s Blessed Circle");
		ITEMS.add("Stormchaser");
		ITEMS.add("Tiamat’s Rebuke");
		ITEMS.add("Kerke’s Sanctuary");
		ITEMS.add("Radimant’s Sphere");
		ITEMS.add("Lidless Wall");
		ITEMS.add("Lance Guard");
		ITEMS.add("Venom Grip");
		ITEMS.add("Gravepalm");
		ITEMS.add("Ghoulhide");
		ITEMS.add("Lavagout");
		ITEMS.add("Hellmouth");
		ITEMS.add("Infernostride");
		ITEMS.add("Waterwalk");
		ITEMS.add("Silkweave");
		ITEMS.add("War Traveler");
		ITEMS.add("Gore Rider");
		ITEMS.add("String of Ears");
		ITEMS.add("Razortail");
		ITEMS.add("Gloomstrap");
		ITEMS.add("Snowclash");
		ITEMS.add("Thundergod’s Vigor");
		ITEMS.add("Harlequin Crest");
		ITEMS.add("Veil of Steel");
		ITEMS.add("Gladiator’s Bane");
		ITEMS.add("Arkaine’s Valor");
		ITEMS.add("Blackoak Shield");
		ITEMS.add("Stormshield");
		ITEMS.add("Hellslayer");
		ITEMS.add("Messerschmidt’s Reaver");
		ITEMS.add("Baranar’s Star");
		ITEMS.add("Schaefer’s Hammer");
		ITEMS.add("Cranium Basher");
		ITEMS.add("Lightsabre");
		ITEMS.add("Doombringer");
		ITEMS.add("Grandfather");
		ITEMS.add("Wizardspike");
		ITEMS.add("Constricting Ring");
		ITEMS.add("Stormspire");
		ITEMS.add("Eaglehorn");
		ITEMS.add("Windforce");
		ITEMS.add("Bul-Katho’s Wedding Band");
		ITEMS.add("Cat’s Eye");
		ITEMS.add("Rising Sun");
		ITEMS.add("Crescent Moon");
		ITEMS.add("Mara’s Kaleidoscope");
		ITEMS.add("Atma’s Scarab");
		ITEMS.add("Dwarf Star");
		ITEMS.add("Ravenfrost");
		ITEMS.add("Highlord’s Wrath");
		ITEMS.add("Saracen’s Chance");
		ITEMS.add("Arreat’s Face");
		ITEMS.add("Homunculus");
		ITEMS.add("Titan’s Revenge");
		ITEMS.add("Lycander’s Aim");
		ITEMS.add("Lycander’s Flank");
		ITEMS.add("Oculus");
		ITEMS.add("Herald of Zakarum");
		ITEMS.add("Bartuc’s Cut-Throat");
		ITEMS.add("Jalal’s Mane");
		ITEMS.add("Scalper");
		ITEMS.add("Bloodmoon");
		ITEMS.add("Djinn Slayer");
		ITEMS.add("Deathbit");
		ITEMS.add("Warshrike");
		ITEMS.add("Gut Siphon");
		ITEMS.add("Razor’s Edge");
		ITEMS.add("Gore Ripper");
		ITEMS.add("Demonlimb");
		ITEMS.add("Steelshade");
		ITEMS.add("Tomb Reaver");
		ITEMS.add("Death’s Web");
		ITEMS.add("Nature’s Peace");
		ITEMS.add("Seraph’s Hymn");
		ITEMS.add("Zakarum’s Salvation");
		ITEMS.add("Fleshripper");
		ITEMS.add("Horizon’s Tornado");
		ITEMS.add("Stone Crusher");
		ITEMS.add("Jade Talon");
		ITEMS.add("Shadow Dancer");
		ITEMS.add("Cerebus’ Bite");
		ITEMS.add("Tyrael’s Might");
		ITEMS.add("Souldrain");
		ITEMS.add("Runemaster");
		ITEMS.add("Deathcleaver");
		ITEMS.add("Executioner’s Justice");
		ITEMS.add("Stoneraven");
		ITEMS.add("Leviathan");
		ITEMS.add("Larzuk’s Champion");
		ITEMS.add("Wisp Projector");
		ITEMS.add("Gargoyle’s Bite");
		ITEMS.add("Lacerator");
		ITEMS.add("Mang Song’s Lesson");
		ITEMS.add("Viperfork");
		ITEMS.add("Ethereal Edge");
		ITEMS.add("Demonhorn’s Edge");
		ITEMS.add("Reaper’s Toll");
		ITEMS.add("Spiritkeeper");
		ITEMS.add("Hellrack");
		ITEMS.add("Alma Negra");
		ITEMS.add("Darkforge Spawn");
		ITEMS.add("Widowmaker");
		ITEMS.add("Bloodraven’s Charge");
		ITEMS.add("Ghostflame");
		ITEMS.add("Shadowkiller");
		ITEMS.add("Gimmershred");
		ITEMS.add("Griffon’s Eye");
		ITEMS.add("Windhammer");
		ITEMS.add("Thunderstroke");
		ITEMS.add("Giantmaimer");
		ITEMS.add("Demon’s Arch");
		ITEMS.add("Boneflame");
		ITEMS.add("Steelpillar");
		ITEMS.add("Nightwing’s Veil");
		ITEMS.add("Crown of Ages");
		ITEMS.add("Andariel’s Visage");
		ITEMS.add("Darkfear");
		ITEMS.add("Dragonscale");
		ITEMS.add("Steel Carapice");
		ITEMS.add("Medusa’s Gaze");
		ITEMS.add("Ravenlore");
		ITEMS.add("Boneshade");
		ITEMS.add("Nethercrow");
		ITEMS.add("Flamebellow");
		ITEMS.add("Fathom");
		ITEMS.add("Wolfhowl");
		ITEMS.add("Spirit Ward");
		ITEMS.add("Kira’s Guardian");
		ITEMS.add("Ormus’ Robes");
		ITEMS.add("Gheed’s Fortune");
		ITEMS.add("Stormlash");
		ITEMS.add("Halaberd’s Reign");
		ITEMS.add("Warriv’s Warder");
		ITEMS.add("Spike Thorn");
		ITEMS.add("Dracul’s Grasp");
		ITEMS.add("Frostwind");
		ITEMS.add("Templar’s Might");
		ITEMS.add("Eschuta’s Temper");
		ITEMS.add("Firelizard’s Talons");
		ITEMS.add("Sandstorm Trek");
		ITEMS.add("Marrowwalk");
		ITEMS.add("Heaven’s Light");
		ITEMS.add("Merman’s Speed");
		ITEMS.add("Arachnid Mesh");
		ITEMS.add("Nosferatu’s Coil");
		ITEMS.add("Metalgrid");
		ITEMS.add("Verdungo’s Hearty Cord");
		ITEMS.add("Carrion Wind");
		ITEMS.add("Giant Skull");
		ITEMS.add("Astreon’s Iron Ward");
		ITEMS.add("Annihilus");
		ITEMS.add("Arioc’s Needle");
		ITEMS.add("Cranebeak");
		ITEMS.add("Nord’s Tenderizer");
		ITEMS.add("Earth Shifter");
		ITEMS.add("Wraith Flight");
		ITEMS.add("Bonehew");
		ITEMS.add("Ondal’s Wisdom");
		ITEMS.add("Reedeemer");
		ITEMS.add("Headhunter’s Glory");
		ITEMS.add("Steelrend");
		ITEMS.add("Rainbow Facet");
		ITEMS.add("Hellfire Torch");
		ITEMS.add("The Redeemer");
		
		ITEMS.add("Trang-Oul’s Girth");
		ITEMS.add("Cow King’s Hide");
		ITEMS.add("Hwanin’s Seal");
		ITEMS.add("Cleglaw’s Claw");
		ITEMS.add("Milabrega’s Robe");
		ITEMS.add("Wilhelm’s Pride");
		ITEMS.add("Isenhart’s Lightbrand");
		ITEMS.add("Berserker’s Hauberk");
		ITEMS.add("Bul-Kathos’ Sacred Charge");
		ITEMS.add("Trang-Oul’s Scales");
		ITEMS.add("Sigon’s Wrap");
		ITEMS.add("Spiritual Custodian");
		ITEMS.add("Cleglaw’s Pincers");
		ITEMS.add("Arctic Binding");
		ITEMS.add("Naj’s Circlet");
		ITEMS.add("Vidala’s Fetlock");
		ITEMS.add("Iratha’s Collar");
		ITEMS.add("Isenhart’s Horns");
		ITEMS.add("Arcanna’s Flesh");
		ITEMS.add("Infernal Torch");
		ITEMS.add("Infernal Cranium");
		ITEMS.add("Tal Rasha’s Guardianship");
		ITEMS.add("Tancred’s Spine");
		ITEMS.add("Immortal King’s Pillar");
		ITEMS.add("Sigon’s Shelter");
		ITEMS.add("Sazabi’s Cobalt Redeemer");
		ITEMS.add("Griswolds’s Redemption");
		ITEMS.add("Tancred’s Skull");
		ITEMS.add("Tancred’s Hobnails");
		ITEMS.add("Natalya’s Shadow");
		ITEMS.add("Ondal’s Almighty");
		ITEMS.add("Haemosu’s Adament");
		ITEMS.add("Immortal King’s Detail");
		ITEMS.add("Griswold’s Valor");
		ITEMS.add("Sigon’s Sabot");
		ITEMS.add("Naj’s Light Plate");
		ITEMS.add("Laying of Hands");
		ITEMS.add("Sazabi’s Ghost Liberator");
		ITEMS.add("Immortal King’s Forge");
		ITEMS.add("Civerb’s Cudgel");
		ITEMS.add("Angelic Mantle");
		ITEMS.add("Natalya’s Soul");
		ITEMS.add("Sazabi’s Mental Sheath");
		ITEMS.add("Vidala’s Snare");
		ITEMS.add("Hsarus’ Iron Stay");
		ITEMS.add("Aldur’s Deception");
		ITEMS.add("Sander’s Taboo");
		ITEMS.add("Sander’s Paragon");
		ITEMS.add("Cathan’s Visage");
		ITEMS.add("Heaven’s Taebaek");
		ITEMS.add("Cathan’s Seal");
		ITEMS.add("Griswold’s Honor");
		ITEMS.add("Cathan’s Rule");
		ITEMS.add("Trang-Oul’s Wing");
		ITEMS.add("Rite of Passage");
		ITEMS.add("Credendum");
		ITEMS.add("Angelic Wings");
		ITEMS.add("Arctic Furs");
		ITEMS.add("Cow King’s Hoofs");
		ITEMS.add("Wihtstan’s Guard");
		ITEMS.add("Sander’s Riprap");
		ITEMS.add("Magnus’ Skin");
		ITEMS.add("Cathan’s Mesh");
		ITEMS.add("Arctic Mitts");
		ITEMS.add("Natalya’s Totem");
		ITEMS.add("M’avina’s Tenet");
		ITEMS.add("Trang-Oul’s Claws");
		ITEMS.add("Milabrega’s Diadem");
		ITEMS.add("Trang-Oul’s Guise");
		ITEMS.add("Angelic Sickle");
		ITEMS.add("Angelic Halo");
		ITEMS.add("Dangoon’s Teaching");
		ITEMS.add("Aldur’s Advance");
		ITEMS.add("Hsarus’ Iron Fist");
		ITEMS.add("Tancred’s Crowbill");
		ITEMS.add("Griswold’s Heart");
		ITEMS.add("M’avina’s Icy Clutch");
		ITEMS.add("Naj’s Puzzler");
		ITEMS.add("Aldur’s Rhythm");
		ITEMS.add("Tal Rasha’s Adjudication");
		ITEMS.add("M’avina’s Embrace");
		ITEMS.add("Hwanin’s Splendor");
		ITEMS.add("Civerb’s Icon");
		ITEMS.add("Tal Rasha’s Fine-Spun Cloth");
		ITEMS.add("Hsarus’ Iron Heel");
		ITEMS.add("Vidala’s Ambush");
		ITEMS.add("Immortal King’s Stone Crusher");
		ITEMS.add("Arctic Horn");
		ITEMS.add("M’avina’s True Sight");
		ITEMS.add("Cow King’s Horns");
		ITEMS.add("Arcanna’s Deathwand");
		ITEMS.add("Death’s Touch");
		ITEMS.add("Arcanna’s Sign");
		ITEMS.add("Guillaume’s Face");
		ITEMS.add("Immortal King’s Will");
		ITEMS.add("Isenhart’s Case");
		ITEMS.add("Aldur’s Stony Gaze");
		ITEMS.add("Hwanin’s Refuge");
		ITEMS.add("Civerb’s Ward");
		ITEMS.add("Berserker’s Headgear");
		ITEMS.add("Hwanin’s Justice");
		ITEMS.add("Milabrega’s Rod");
		ITEMS.add("Infernal Sign");
		ITEMS.add("Tal Rasha’s Horadric Crest");
		ITEMS.add("Iratha’s Cuff");
		ITEMS.add("Tal Rasha’s Lidless Eye");
		ITEMS.add("Natalya’s Mark");
		ITEMS.add("Cathan’s Sigil");
		ITEMS.add("Berserker’s Hatchet");
		ITEMS.add("Death’s Hand");
		ITEMS.add("Sigon’s Visor");
		ITEMS.add("Arcanna’s Head");
		ITEMS.add("Iratha’s Cord");
		ITEMS.add("Isenhart’s Parry");
		ITEMS.add("Sigon’s Gage");
		ITEMS.add("Tancred’s Weird");
		ITEMS.add("Vidala’s Barb");
		ITEMS.add("Sigon’s Guard");
		ITEMS.add("Death’s Guard");
		ITEMS.add("Immortal King’s Soul Cage");
		ITEMS.add("Bul-Kathos’ Tribal Guardian");
		ITEMS.add("Sander’s Superstition");
		ITEMS.add("Iratha’s Coil");
		ITEMS.add("Cleglaw’s Tooth");
		ITEMS.add("Milabrega’s Orb");
		ITEMS.add("M’avina’s Caster");
		ITEMS.add("Telling of Beads");
		
		ITEMS.add("Delirium");
		ITEMS.add("Memory");
		ITEMS.add("Splendor");
		ITEMS.add("Black");
		ITEMS.add("Grief");
		ITEMS.add("Rhyme");
		ITEMS.add("Dream");
		ITEMS.add("Last Wish");
		ITEMS.add("Harmony");
		ITEMS.add("Principle");
		ITEMS.add("Lore");
		ITEMS.add("Passion");
		ITEMS.add("Melody");
		ITEMS.add("King’s Grace");
		ITEMS.add("Prudence");
		ITEMS.add("Dragon");
		ITEMS.add("Bramble");
		ITEMS.add("Famine");
		ITEMS.add("Leaf");
		ITEMS.add("Call to Arms");
		ITEMS.add("Honor");
		ITEMS.add("Kingslayer");
		ITEMS.add("Infinity");
		ITEMS.add("Ice");
		ITEMS.add("Steel");
		ITEMS.add("Fortitude");
		ITEMS.add("Silence");
		ITEMS.add("Gloom");
		ITEMS.add("Breath of the Dying");
		ITEMS.add("Chaos");
		ITEMS.add("Beast");
		ITEMS.add("Enlightenment");
		ITEMS.add("Enigma");
		ITEMS.add("Doom");
		ITEMS.add("Smoke");
		ITEMS.add("Zephyr");
		//ITEMS.add("Stone");
		ITEMS.add("Rain");
		ITEMS.add("Lionheart");
		ITEMS.add("Radiance");
		ITEMS.add("Insight");
		ITEMS.add("Nadir");
		ITEMS.add("Duress");
		ITEMS.add("Brand");
		ITEMS.add("Stealth");
		ITEMS.add("Death");
		ITEMS.add("Malice");
		ITEMS.add("Heart of the Oak");
		ITEMS.add("Ancient’s Pledge");
		ITEMS.add("Oath");
		ITEMS.add("Destruction");
		ITEMS.add("Exile");
		ITEMS.add("Pride");
		ITEMS.add("Treachery");
		ITEMS.add("Peace");
		ITEMS.add("Holy Thunder");
		ITEMS.add("Phoenix");
		ITEMS.add("Hand of Justice");
		ITEMS.add("Obedience");
		ITEMS.add("Faith");
		ITEMS.add("Eternity");
		ITEMS.add("Spirit");
		ITEMS.add("Lawbringer");
		ITEMS.add("White");
		ITEMS.add("Bone");
		ITEMS.add("Edge");
		//ITEMS.add("Strength");
		ITEMS.add("Wealth");
		ITEMS.add("Chains of Honor");
		
		ITEMS.sort(Comparator.comparingInt(String::length).reversed());
		//THINGS.add("");
		
		ABBREVIATIONS.put("CTA", "Call to Arms");
		//ABBREVIATIONS.put(" res", " Resistances");
		ABBREVIATIONS.put("FHR", "Faster Hit Recovery");
		ABBREVIATIONS.put("FCR", "Faster Cast Rate");
		ABBREVIATIONS.put("FRW", "Faster Run/Walk");
		ABBREVIATIONS.put("FBR", "Faster Block Rate");
		ABBREVIATIONS.put("IAS", "Increased Attack Speed");
		ABBREVIATIONS.put("NHAM", "'Next Hit Always Misses'");
		//ABBREVIATIONS.put("Monarch", "Monarch Shield");
		//ABBREVIATIONS.put("Light", "Lightning");
		ABBREVIATIONS.put("Facet", "Rainbow Facet");
		ABBREVIATIONS.put(" + ", " and ");
		ABBREVIATIONS.put("Buriza", "Buriza-Do Kyanon");
		ABBREVIATIONS.put("Lidless", "Lidless Wall");
		ABBREVIATIONS.put("Torch", "Hellfire Torch");
		ABBREVIATIONS.put("Hsarus’ Boots", "Hsarus’ Iron Heel");
		ABBREVIATIONS.put("Hsarus Boots", "Hsarus’ Iron Heel");
		ABBREVIATIONS.put("Verdungo’s", "Verdungo’s Hearty Cord");
		ABBREVIATIONS.put("Bul Kathos", "Bul-Katho’s Wedding Band");
		ABBREVIATIONS.put("Shako", "Harlequin Crest");
		ABBREVIATIONS.put("Trangs", "Trang-Oul’s Claws");
		ABBREVIATIONS.put("Throw Mastery", "Throwing Mastery");
		ABBREVIATIONS.put("Vipermagi", "Skin of the Vipermagi");
		ABBREVIATIONS.put("Que Hagans", "Que-Hegan’s Wisdom");
		ABBREVIATIONS.put("Que Hegans", "Que-Hegan’s Wisdom");
		ABBREVIATIONS.put("Kira’s", "Kira’s Guardian");
		ABBREVIATIONS.put("Dracul’s", "Dracul’s Grasp");
		ABBREVIATIONS.put("Trang Oul’s Claw", "Trang-Oul’s Claws");
		ABBREVIATIONS.put("Trang-Oul’s Claw", "Trang-Oul’s Claws");
		ABBREVIATIONS.put("Trang Gloves", "Trang-Oul’s Claws");
		ABBREVIATIONS.put("Iratha’s", "Iratha’s Coil");
		ABBREVIATIONS.put("Sigon’s Shield", "Sigon’s Guard");
		ABBREVIATIONS.put("Static", "Static Field");
		ABBREVIATIONS.put("Gheeds", "Gheed’s Fortune");
		ABBREVIATIONS.put("Tal Rasha’s Armor", "Tal Rasha’s Guardianship");
		ABBREVIATIONS.put("Tal Rasha’s Belt", "Tal Rasha’s Fine-Spun Cloth");
		ABBREVIATIONS.put("Tal Rasha’s Amulet", "Tal Rasha’s Adjudication");
		ABBREVIATIONS.put("Andariel’s Helm", "Andariel’s Visage");
		ABBREVIATIONS.put("GCs", "Grand Charms");
		ABBREVIATIONS.put("SCs", "Small Charms");
		ABBREVIATIONS.put("scs", "Small Charms");
		//ABBREVIATIONS.put("Str", "Strength");
		ABBREVIATIONS.put("Dex", "Dexterity");
		ABBREVIATIONS.put("Vit", "Vitality");
		ABBREVIATIONS.put("Ene", "Energy");
		ABBREVIATIONS.put("Bartucs", "Bartuc’s Cut-Throat");
		//ABBREVIATIONS.put("", "");
		
		// typos
		// idiot
		ABBREVIATIONS.put("Waterwalks", "Waterwalk");
		ABBREVIATIONS.put("Javlin", "Javelin");
		ABBREVIATIONS.put("Angelic’s", "Angelic");
		ABBREVIATIONS.put("Angelics", "Angelic");
		ABBREVIATIONS.put("Chain of Honor", "Chains of Honor");
		ABBREVIATIONS.put("Slow Missile", "Slow Missiles");
		ABBREVIATIONS.put("Trang Oul’s", "Trang-Oul’s");
		ABBREVIATIONS.put("Thundergod’s Might", "Thundergod’s Vigor");
		ABBREVIATIONS.put("StormShield", "Stormshield");
		ABBREVIATIONS.put("Thunderstorm", "Thunder Storm");
		ABBREVIATIONS.put("Fireblast", "Fire Blast");
		ABBREVIATIONS.put("Dwarfstar", "Dwarf Star");
		ABBREVIATIONS.put("Heart of the Wolverine", "Heart of Wolverine");
		ABBREVIATIONS.put("Lightsaber", "Lightsabre");
		ABBREVIATIONS.put("Immortal King’s Stone Crushed", "Immortal King’s Stone Crusher");
		ABBREVIATIONS.put("AssassinTorch", "Assassin Torch");
		//ABBREVIATIONS.put("", "");
		
		GRAMMAR.add("fhr");
		GRAMMAR.add("Fhr");
		GRAMMAR.add("fcr");
		GRAMMAR.add("life");
		GRAMMAR.add("frw");
		GRAMMAR.add("grand charm");
		GRAMMAR.add("small charm");
		GRAMMAR.add("large charm");
		GRAMMAR.add("mana");
		GRAMMAR.add("strength");
		GRAMMAR.add("minion");
		GRAMMAR.add("soft skills");
		GRAMMAR.add("items");
		GRAMMAR.add("leech");
		GRAMMAR.add("charms");
		GRAMMAR.add("small Charms");
		GRAMMAR.add("damage");
		GRAMMAR.add("elemental immunity");
		GRAMMAR.add("stats");
		GRAMMAR.add("Damage reduction");
		GRAMMAR.add("venom");
		GRAMMAR.add("skiller");
		GRAMMAR.add("shield");
		GRAMMAR.add("Fire ball");
		GRAMMAR.add("Fire bolt");
		GRAMMAR.add("unique");
		GRAMMAR.add("physical");
		GRAMMAR.add("fire");
		//GRAMMAR.add("");
		
		HARDCODES.put("@@@D2Annihilus@@@", "@@@D2AnnihilusCharm@@@");
		HARDCODES.put("@@@D2Zeal@@@ot", "Zealot");
		HARDCODES.put("Resistancesistance", "Resistance");
		HARDCODES.put("@@@D2Teleport@@@s", "Teleports");
		HARDCODES.put("@@@D2VerdungosHeartyCord@@@ Hearty Cord", "@@@D2VerdungosHeartyCord@@@");
		HARDCODES.put("@@@D2Meteor@@@b", "Meteorb");
		HARDCODES.put("Tal Rasha’s @@@D2LidlessWall@@@ Eye", "@@@D2TalRashasLidlessEye@@@");
		HARDCODES.put("@@@D2Chaos@@@ Sanctuary", "Chaos Sanctuary");
		HARDCODES.put("@@@D2Enchant@@@ress", "Enchantress");
		HARDCODES.put("@@@D2Bone@@@ Necromancer", "Bone Necromancer");
		HARDCODES.put("@@@D2HarlequinCrest@@@ @@@D2HarlequinCrest@@@", "@@@D2HarlequinCrest@@@");
		HARDCODES.put("@@@D2Spirit@@@ Shield", "@@@D2Spirit@@@");
		HARDCODES.put("Paladin@@@D2HellfireTorch@@@", "Paladin @@@D2HellfireTorch@@@");
		HARDCODES.put("@@@D2Enchant@@@ing", "Enchanting");
		HARDCODES.put("@@@D2AnnihilusCharm@@@ Charm", "@@@D2AnnihilusCharm@@@");
		HARDCODES.put("Fhr", "Faster Hit Recovery");
		HARDCODES.put("Fcr", "Faster Cast Rate");
		HARDCODES.put("Frw", "Faster Run/Walk");
		HARDCODES.put("Fbr", "Faster Block Rate");
		HARDCODES.put("Ias", "Increased Attack Speed");
		HARDCODES.put("Strengthength", "Strength");
		HARDCODES.put("Dexterityterity", "Dexterity");
		HARDCODES.put("Vitalityality", "Vitality");
		HARDCODES.put("Energyrgy", "Energy");
		HARDCODES.put("Strengthing of Ears", "@@@D2StringOfEars@@@");
		HARDCODES.put("Assassin@@@D2HellfireTorch@@@", "Assassin @@@D2HellfireTorch@@@");
		HARDCODES.put("Deadly Strengthike", "Deadly Strike");
		HARDCODES.put("On Strengthiking", "On Striking");
		HARDCODES.put("Rainbow @@@D2RainbowFacet@@@", "@@@D2RainbowFacet@@@");
		HARDCODES.put("@@@D2Raven@@@ Frost", "@@@D2RavenFrost@@@");
		HARDCODES.put("@@@D2Smite@@@r", "Smiter");
		HARDCODES.put("@@@D2GoreRider@@@s", "@@@D2GoreRider@@@");
		HARDCODES.put("@@@D2Charge@@@d Strengthike", "@@@D2ChargedStrike@@@");
		HARDCODES.put("@@@D2Charge@@@d Strike", "@@@D2ChargedStrike@@@");
		
	}
	
	public static String format(String line, String build) {
		line = line.replace("%build_name%", build);
		line = line.replace("'", "’");
		for (String s : GRAMMAR) {
			line = line.replace(s, WordUtils.capitalize(s));
		}
		for (Map.Entry<String, String> entry : ABBREVIATIONS.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		for (String thing : SKILLS) {
			if (!line.contains("@D2" + thing) && !line.contains(thing + "@")) {
				line = line.replace(thing, String.format("@@@D2%s@@@", WordUtils.capitalize(thing).replaceAll("[- '’]", "")));
			}
		}
		for (String thing : ITEMS) {
			if (!line.contains("@D2" + thing) && !line.contains(thing + "@")) {
				line = line.replace(thing, String.format("@@@D2%s@@@", WordUtils.capitalize(thing).replaceAll("[- '’]", "")));
			}
		}
		for (Map.Entry<String, String> entry : HARDCODES.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		return line.trim();
	}
	
	public static String formatOnlyItems(String line, String build) {
		line = line.replace("%build_name%", build);
		line = line.replace("'", "’");
		for (String s : GRAMMAR) {
			line = line.replace(s, WordUtils.capitalize(s));
		}
		for (Map.Entry<String, String> entry : ABBREVIATIONS.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		for (String thing : ITEMS) {
			if (!line.contains("@D2" + thing) && !line.contains(thing + "@")) {
				line = line.replace(thing, String.format("@@@D2%s@@@", WordUtils.capitalize(thing).replaceAll("[- '’]", "")));
			}
		}
		for (Map.Entry<String, String> entry : HARDCODES.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		return line.trim();
	}
	
	public static String formatOnlySkills(String line, String build) {
		line = line.replace("%build_name%", build);
		line = line.replace("'", "’");
		for (String s : GRAMMAR) {
			line = line.replace(s, WordUtils.capitalize(s));
		}
		for (Map.Entry<String, String> entry : ABBREVIATIONS.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		for (String thing : SKILLS) {
			if (!line.contains("@D2" + thing) && !line.contains(thing + "@")) {
				line = line.replace(thing, String.format("@@@D2%s@@@", WordUtils.capitalize(thing).replaceAll("[- '’]", "")));
			}
		}
		for (Map.Entry<String, String> entry : HARDCODES.entrySet()) {
			line = line.replace(entry.getKey(), entry.getValue());
		}
		return line.trim();
	}
	
}
